<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\DB;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;


class PositionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $positions = [
            ['name'=>'Администратор', 'is_entered'=>true, 'entered_at'=>'01.10.2020', 'is_excluded'=>false],
            ['name'=>'Архивист I кат.', 'is_entered'=>true, 'entered_at'=>'01.01.2018', 'is_excluded'=>false],
            ['name'=>'Банщик', 'is_entered'=>true, 'entered_at'=>'01.01.2020', 'is_excluded'=>false],
            ['name'=>'Бухгалтер', 'is_entered'=>true, 'entered_at'=>'01.01.2018', 'is_excluded'=>false],
            ['name'=>'Бухгалтер 1 категории', 'is_entered'=>true, 'entered_at'=>'01.01.2017', 'is_excluded'=>false],
            ['name'=>'Бухгалтер 2 категории', 'is_entered'=>true, 'entered_at'=>'01.01.2019', 'is_excluded'=>false],
            ['name'=>'Бухгалтер 3/1', 'is_entered'=>true, 'entered_at'=>'01.01.2018', 'is_excluded'=>false],
            ['name'=>'Бухгалтер 3/4', 'is_entered'=>true, 'entered_at'=>'01.01.2018', 'is_excluded'=>false],
            ['name'=>'в отставке', 'is_entered'=>false, 'entered_at'=>'01.01.2020', 'is_excluded'=>false],
            ['name'=>'Вед. архивист', 'is_entered'=>true, 'entered_at'=>'01.01.2020', 'is_excluded'=>false],
            ['name'=>'Ведущий бухгалтер', 'is_entered'=>true, 'entered_at'=>'01.01.2017', 'is_excluded'=>false],
            ['name'=>'Ведущий документовед', 'is_entered'=>true, 'entered_at'=>'01.01.2017', 'is_excluded'=>false],
            ['name'=>'Ведущий инженер', 'is_entered'=>true, 'entered_at'=>'01.01.2017', 'is_excluded'=>false],
            ['name'=>'Ведущий инженер по техническому надзору', 'is_entered'=>true, 'entered_at'=>'01.01.2017', 'is_excluded'=>false],
            ['name'=>'Ведущий инженер-програмист', 'is_entered'=>true, 'entered_at'=>'01.01.2017', 'is_excluded'=>false],
            ['name'=>'Ведущий программист', 'is_entered'=>true, 'entered_at'=>'01.01.2018', 'is_excluded'=>false],
            ['name'=>'Ведущий специалист', 'is_entered'=>true, 'entered_at'=>'16.10.2019', 'is_excluded'=>false],
            ['name'=>'Ведущий специалист градостроительства', 'is_entered'=>false, 'entered_at'=>'01.01.2019', 'is_excluded'=>false],
            ['name'=>'ведущий специалист по конкурсам и аукционам', 'is_entered'=>true, 'entered_at'=>'01.01.2019', 'is_excluded'=>false],
            ['name'=>'Ведущий специалист по охране труда', 'is_entered'=>true, 'entered_at'=>'01.01.2017', 'is_excluded'=>false],
            ['name'=>'Ведущий специалист по связям с общественностью', 'is_entered'=>true, 'entered_at'=>'01.01.2017', 'is_excluded'=>false],
            ['name'=>'Ведущий специалист по технической поддержке информационно-коммуниуационных систем', 'is_entered'=>true, 'entered_at'=>'01.01.2021', 'is_excluded'=>false],
            ['name'=>'Ведущий экономист', 'is_entered'=>true, 'entered_at'=>'01.01.2017', 'is_excluded'=>false],
            ['name'=>'Ведущий юрисконсульт', 'is_entered'=>true, 'entered_at'=>'01.01.2017', 'is_excluded'=>false],
            ['name'=>'Водитель', 'is_entered'=>true, 'entered_at'=>'01.01.2017', 'is_excluded'=>false],
            ['name'=>'Гардеробщик', 'is_entered'=>true, 'entered_at'=>'01.01.2018', 'is_excluded'=>false],
            ['name'=>'Глава Петрозаводского городского округа', 'is_entered'=>true, 'entered_at'=>'01.01.2020', 'is_excluded'=>false],
            ['name'=>'Главный архивист', 'is_entered'=>true, 'entered_at'=>'01.01.2018', 'is_excluded'=>false],
            ['name'=>'Главный бухгалтер', 'is_entered'=>true, 'entered_at'=>'01.01.2017', 'is_excluded'=>false],
            ['name'=>'Главный специалист', 'is_entered'=>true, 'entered_at'=>'01.01.2017', 'is_excluded'=>false],
            ['name'=>'Главный специалист по делопроизводству', 'is_entered'=>true, 'entered_at'=>'01.03.2020', 'is_excluded'=>false],
            ['name'=>'Главный специалист по закупкам(контрактный управляющий)', 'is_entered'=>true, 'entered_at'=>'01.10.2019', 'is_excluded'=>false],
            ['name'=>'Главный специалист по приему и обработке экстренных вызовов', 'is_entered'=>true, 'entered_at'=>'01.07.2020', 'is_excluded'=>false],
            ['name'=>'Главный специалист по связям с общественностью', 'is_entered'=>true, 'entered_at'=>'01.06.2019', 'is_excluded'=>false],
            ['name'=>'Главный специалист по системе 112', 'is_entered'=>true, 'entered_at'=>'01.10.2021', 'is_excluded'=>false],
            ['name'=>'Главный специалист-эксперт', 'is_entered'=>true, 'entered_at'=>'01.03.2020', 'is_excluded'=>false],
            ['name'=>'Главный юрист', 'is_entered'=>true, 'entered_at'=>'01.01.2017', 'is_excluded'=>false],
            ['name'=>'Дворник', 'is_entered'=>true, 'entered_at'=>'01.01.2020', 'is_excluded'=>false],
            ['name'=>'Делопроизводитель', 'is_entered'=>true, 'entered_at'=>'01.01.2018', 'is_excluded'=>false],
            ['name'=>'Директор', 'is_entered'=>true, 'entered_at'=>'01.01.2017', 'is_excluded'=>false],
            ['name'=>'Диспетчер', 'is_entered'=>true, 'entered_at'=>'01.01.2018', 'is_excluded'=>false],
            ['name'=>'Документовед', 'is_entered'=>true, 'entered_at'=>'01.01.2018', 'is_excluded'=>false],
            ['name'=>'Зав кладбищем', 'is_entered'=>true, 'entered_at'=>'01.01.2018', 'is_excluded'=>false],
            ['name'=>'Заведующий баней', 'is_entered'=>true, 'entered_at'=>'01.06.2020', 'is_excluded'=>false],
            ['name'=>'Заведующий копировально-множительным бюро', 'is_entered'=>true, 'entered_at'=>'01.01.2018', 'is_excluded'=>false],
            ['name'=>'Заведующийгаражом', 'is_entered'=>true, 'entered_at'=>'01.01.2018', 'is_excluded'=>false],
            ['name'=>'Зам. главного бухгалтера-начальник отдела', 'is_entered'=>true, 'entered_at'=>'01.01.2022', 'is_excluded'=>false],
            ['name'=>'Зам.директора', 'is_entered'=>true, 'entered_at'=>'01.01.2018', 'is_excluded'=>false],
            ['name'=>'Заместитель главного бухгалтера-начальник отдела', 'is_entered'=>false, 'entered_at'=>'01.01.2019', 'is_excluded'=>false],
            ['name'=>'Заместитель главы Администрации ПГО - руководитель аппарата', 'is_entered'=>true, 'entered_at'=>'01.01.2020', 'is_excluded'=>false],
            ['name'=>'Заместитель главы Администрации Петрозаводского городского округа - председатель комитета', 'is_entered'=>true, 'entered_at'=>'01.01.2020', 'is_excluded'=>false],
            ['name'=>'Заместитель директора', 'is_entered'=>true, 'entered_at'=>'01.01.2017', 'is_excluded'=>false],
            ['name'=>'Заместитель директора по техническим вопросам', 'is_entered'=>true, 'entered_at'=>'06.12.2018', 'is_excluded'=>false],
            ['name'=>'Заместитель начальника', 'is_entered'=>true, 'entered_at'=>'01.01.2017', 'is_excluded'=>false],
            ['name'=>'Заместитель начальника отдела', 'is_entered'=>true, 'entered_at'=>'15.03.2022', 'is_excluded'=>false],
            ['name'=>'Заместитель начальника отдела в составе управления', 'is_entered'=>true, 'entered_at'=>'01.01.2020', 'is_excluded'=>false],
            ['name'=>'Заместитель начальника отдела по орган дор движ и трансп', 'is_entered'=>true, 'entered_at'=>'01.01.2022', 'is_excluded'=>false],
            ['name'=>'Заместитель начальника управления', 'is_entered'=>true, 'entered_at'=>'01.01.2020', 'is_excluded'=>false],
            ['name'=>'Заместитель начальника управления - начальник отдела', 'is_entered'=>true, 'entered_at'=>'01.01.2020', 'is_excluded'=>false],
            ['name'=>'Заместитель председателя комитета - начальник управления', 'is_entered'=>true, 'entered_at'=>'01.01.2020', 'is_excluded'=>false],
            ['name'=>'Заместитель руководителя', 'is_entered'=>true, 'entered_at'=>'01.01.2018', 'is_excluded'=>false],
            ['name'=>'И. о. руководителя', 'is_entered'=>true, 'entered_at'=>'01.01.2022', 'is_excluded'=>false],
            ['name'=>'И.о. директора', 'is_entered'=>true, 'entered_at'=>'01.01.2017', 'is_excluded'=>false],
            ['name'=>'Инженер 1 категории', 'is_entered'=>true, 'entered_at'=>'01.01.2017', 'is_excluded'=>false],
            ['name'=>'Инженер по безопасности дорожного движения', 'is_entered'=>true, 'entered_at'=>'01.06.2019', 'is_excluded'=>false],
            ['name'=>'Инженер по гражданскому строительству', 'is_entered'=>false, 'entered_at'=>'01.01.2019', 'is_excluded'=>false],
            ['name'=>'Инженер по информационным технологиям', 'is_entered'=>true, 'entered_at'=>'01.01.2019', 'is_excluded'=>false],
            ['name'=>'Инженер по капитальному строительству', 'is_entered'=>true, 'entered_at'=>'01.01.2018', 'is_excluded'=>false],
            ['name'=>'Инженер по проектно сметной документации', 'is_entered'=>true, 'entered_at'=>'01.01.2019', 'is_excluded'=>false],
            ['name'=>'Инженер по проектно-сметной работе', 'is_entered'=>true, 'entered_at'=>'01.01.2018', 'is_excluded'=>false],
            ['name'=>'Инженер по техническому надзору', 'is_entered'=>true, 'entered_at'=>'01.01.2018', 'is_excluded'=>false],
            ['name'=>'инженер производсивенного отдела', 'is_entered'=>true, 'entered_at'=>'01.01.2018', 'is_excluded'=>false],
            ['name'=>'Инженер-энергетик', 'is_entered'=>true, 'entered_at'=>'01.01.2018', 'is_excluded'=>false],
            ['name'=>'инспектор по договорной и претензионной работе', 'is_entered'=>true, 'entered_at'=>'01.01.2018', 'is_excluded'=>false],
            ['name'=>'Инспектор по договорной и претензионной работе 1 категории', 'is_entered'=>true, 'entered_at'=>'01.01.2019', 'is_excluded'=>false],
            ['name'=>'инспектор по договорной и претензионной работе 2 кат', 'is_entered'=>true, 'entered_at'=>'01.01.2019', 'is_excluded'=>false],
            ['name'=>'Инспектор по договорной и претензионной работе 2 категории', 'is_entered'=>true, 'entered_at'=>'01.01.2018', 'is_excluded'=>false],
            ['name'=>'Инспектор по договорной работе', 'is_entered'=>true, 'entered_at'=>'01.01.2019', 'is_excluded'=>false],
            ['name'=>'Консультант', 'is_entered'=>true, 'entered_at'=>'01.01.2020', 'is_excluded'=>false],
            ['name'=>'Консультант - заместитель начальника отдела', 'is_entered'=>true, 'entered_at'=>'01.01.2020', 'is_excluded'=>false],
            ['name'=>'Консультант по закупкам', 'is_entered'=>true, 'entered_at'=>'01.01.2019', 'is_excluded'=>false],
            ['name'=>'Консультант по общим вопросам', 'is_entered'=>true, 'entered_at'=>'22.02.2023', 'is_excluded'=>false],
            ['name'=>'Консультант по претензионной работе', 'is_entered'=>false, 'entered_at'=>'01.01.2019', 'is_excluded'=>false],
            ['name'=>'Контрактный управляющий', 'is_entered'=>true, 'entered_at'=>'01.01.2019', 'is_excluded'=>false],
            ['name'=>'Мастер хозяйственно-технического участка', 'is_entered'=>true, 'entered_at'=>'01.01.2018', 'is_excluded'=>false],
            ['name'=>'менеджер', 'is_entered'=>true, 'entered_at'=>'01.01.2018', 'is_excluded'=>false],
            ['name'=>'Младший юрист', 'is_entered'=>true, 'entered_at'=>'01.11.2023', 'is_excluded'=>false],
            ['name'=>'Начальник отдела', 'is_entered'=>true, 'entered_at'=>'01.01.2017', 'is_excluded'=>false],
            ['name'=>'Начальник отдела аналитического учета,расчетов и отчетности', 'is_entered'=>false, 'entered_at'=>'01.01.2019', 'is_excluded'=>false],
            ['name'=>'Начальник отдела в составе управления', 'is_entered'=>true, 'entered_at'=>'01.01.2020', 'is_excluded'=>false],
            ['name'=>'Начальник отдела по претензионной работе', 'is_entered'=>false, 'entered_at'=>'01.01.2019', 'is_excluded'=>false],
            ['name'=>'Начальник отдела технологического и программного обеспечения', 'is_entered'=>true, 'entered_at'=>'01.01.2018', 'is_excluded'=>false],
            ['name'=>'Начальник отделения', 'is_entered'=>true, 'entered_at'=>'01.01.2018', 'is_excluded'=>false],
            ['name'=>'Начальник самостоятельного отдела', 'is_entered'=>true, 'entered_at'=>'01.01.2020', 'is_excluded'=>false],
            ['name'=>'Начальник управления', 'is_entered'=>true, 'entered_at'=>'01.01.2020', 'is_excluded'=>false],
            ['name'=>'Не указана', 'is_entered'=>true, 'entered_at'=>'01.01.2018', 'is_excluded'=>false],
            ['name'=>'Оперативный дежурный', 'is_entered'=>true, 'entered_at'=>'01.01.2018', 'is_excluded'=>false],
            ['name'=>'оператор дежурно-пропускногорежима', 'is_entered'=>true, 'entered_at'=>'01.01.2018', 'is_excluded'=>false],
            ['name'=>'Ответственный за электрохозяйство', 'is_entered'=>true, 'entered_at'=>'20.02.2019', 'is_excluded'=>false],
            ['name'=>'Первый заместитель главы Администрации Петрозаводского городского округа', 'is_entered'=>true, 'entered_at'=>'22.03.2021', 'is_excluded'=>false],
            ['name'=>'Помощник ОД', 'is_entered'=>true, 'entered_at'=>'01.01.2018', 'is_excluded'=>false],
            ['name'=>'Помощник ОД (сист112)', 'is_entered'=>true, 'entered_at'=>'01.10.2019', 'is_excluded'=>false],
            ['name'=>'Председатель комитета', 'is_entered'=>true, 'entered_at'=>'01.01.2020', 'is_excluded'=>false],
            ['name'=>'прочий обслуживающий персонал', 'is_entered'=>true, 'entered_at'=>'01.01.2017', 'is_excluded'=>false],
            ['name'=>'рабочий по комплексному обслуживанию и ремонту зданий', 'is_entered'=>true, 'entered_at'=>'01.01.2018', 'is_excluded'=>false],
            ['name'=>'Рабочий по комплексному обслуживанию территорий', 'is_entered'=>true, 'entered_at'=>'01.04.2022', 'is_excluded'=>false],
            ['name'=>'Руководитель', 'is_entered'=>true, 'entered_at'=>'01.01.2018', 'is_excluded'=>false],
            ['name'=>'Руководитель МКУ ЦБО', 'is_entered'=>true, 'entered_at'=>'01.01.2021', 'is_excluded'=>false],
            ['name'=>'Руководитель-главный бухгалтер', 'is_entered'=>true, 'entered_at'=>'01.01.2022', 'is_excluded'=>false],
            ['name'=>'Секретарь (делопроизводиетль)', 'is_entered'=>true, 'entered_at'=>'01.01.2019', 'is_excluded'=>false],
            ['name'=>'Секретарь руководителя', 'is_entered'=>true, 'entered_at'=>'01.01.2018', 'is_excluded'=>false],
            ['name'=>'Сист. админ.', 'is_entered'=>true, 'entered_at'=>'01.01.2018', 'is_excluded'=>false],
            ['name'=>'Слесарь', 'is_entered'=>true, 'entered_at'=>'01.01.2017', 'is_excluded'=>false],
            ['name'=>'Слесарь по ремонту автомобилей', 'is_entered'=>true, 'entered_at'=>'01.01.2018', 'is_excluded'=>false],
            ['name'=>'Советник Главы Петрозаводского городского округа', 'is_entered'=>true, 'entered_at'=>'01.01.2020', 'is_excluded'=>false],
            ['name'=>'Спец. по выдаче эл.паспортов', 'is_entered'=>true, 'entered_at'=>'01.01.2018', 'is_excluded'=>false],
            ['name'=>'Специалист 1 категории', 'is_entered'=>true, 'entered_at'=>'01.01.2020', 'is_excluded'=>false],
            ['name'=>'Специалист в сфере закупок', 'is_entered'=>true, 'entered_at'=>'01.01.2018', 'is_excluded'=>false],
            ['name'=>'Специалист градостроительства', 'is_entered'=>false, 'entered_at'=>'01.01.2019', 'is_excluded'=>false],
            ['name'=>'Специалист по администрированию сетевых устройств информационно-коммуникационных систем', 'is_entered'=>true, 'entered_at'=>'01.01.2018', 'is_excluded'=>false],
            ['name'=>'Специалист по архивным данным', 'is_entered'=>true, 'entered_at'=>'01.12.2022', 'is_excluded'=>false],
            ['name'=>'Специалист по договорной работе и закупкам', 'is_entered'=>false, 'entered_at'=>'01.01.2019', 'is_excluded'=>false],
            ['name'=>'Специалист по закупкам', 'is_entered'=>true, 'entered_at'=>'01.01.2018', 'is_excluded'=>false],
            ['name'=>'Специалист по инвентаризации земли', 'is_entered'=>true, 'entered_at'=>'01.01.2018', 'is_excluded'=>false],
            ['name'=>'Специалист по кадрам', 'is_entered'=>true, 'entered_at'=>'01.01.2017', 'is_excluded'=>false],
            ['name'=>'Специалист по материально-техническому снабжению', 'is_entered'=>true, 'entered_at'=>'01.01.2018', 'is_excluded'=>false],
            ['name'=>'Специалист по ОТ', 'is_entered'=>true, 'entered_at'=>'01.01.2018', 'is_excluded'=>false],
            ['name'=>'Специалист по связям с общественностью', 'is_entered'=>true, 'entered_at'=>'01.06.2019', 'is_excluded'=>false],
            ['name'=>'Специалист по технической поддержке информационно-коммуникационных систем', 'is_entered'=>true, 'entered_at'=>'01.01.2018', 'is_excluded'=>false],
            ['name'=>'Специалист по управлению персоналом', 'is_entered'=>true, 'entered_at'=>'01.01.2018', 'is_excluded'=>false],
            ['name'=>'Специалист техподд 3/4', 'is_entered'=>true, 'entered_at'=>'01.01.2018', 'is_excluded'=>false],
            ['name'=>'Специалистпо охране труда', 'is_entered'=>true, 'entered_at'=>'01.01.2021', 'is_excluded'=>false],
            ['name'=>'Специалист-эксперт по земельным правоотношениям', 'is_entered'=>false, 'entered_at'=>'01.01.2019', 'is_excluded'=>false],
            ['name'=>'Специлист по договорной работе и закупкам', 'is_entered'=>true, 'entered_at'=>'01.01.2023', 'is_excluded'=>false],
            ['name'=>'Старший инспектор по договорной и претензионной работе', 'is_entered'=>true, 'entered_at'=>'01.01.2019', 'is_excluded'=>false],
            ['name'=>'Старший инспектор по договорной работе', 'is_entered'=>true, 'entered_at'=>'01.01.2018', 'is_excluded'=>false],
            ['name'=>'Старший оператор дежурно-пропускного режима', 'is_entered'=>true, 'entered_at'=>'01.01.2018', 'is_excluded'=>false],
            ['name'=>'Сторож гаража', 'is_entered'=>true, 'entered_at'=>'01.01.2018', 'is_excluded'=>false],
            ['name'=>'Телефонист', 'is_entered'=>true, 'entered_at'=>'01.01.2018', 'is_excluded'=>false],
            ['name'=>'Техник по гражданскому строительству', 'is_entered'=>true, 'entered_at'=>'07.07.2023', 'is_excluded'=>false],
            ['name'=>'Уборщик', 'is_entered'=>true, 'entered_at'=>'01.01.2018', 'is_excluded'=>false],
            ['name'=>'Уборщик территории 3 разряда', 'is_entered'=>true, 'entered_at'=>'01.01.2018', 'is_excluded'=>false],
            ['name'=>'Уборщик служебных помещений', 'is_entered'=>true, 'entered_at'=>'01.01.2018', 'is_excluded'=>false],
            ['name'=>'Уборщица', 'is_entered'=>true, 'entered_at'=>'01.01.2018', 'is_excluded'=>false],
            ['name'=>'уборщица служебных помещений', 'is_entered'=>true, 'entered_at'=>'01.01.2017', 'is_excluded'=>false],
            ['name'=>'Управляющий делами-заместитель руководителя аппарата', 'is_entered'=>true, 'entered_at'=>'01.01.2020', 'is_excluded'=>false],
            ['name'=>'Экономист', 'is_entered'=>true, 'entered_at'=>'01.01.2019', 'is_excluded'=>false],
            ['name'=>'Экономист 1 категории', 'is_entered'=>true, 'entered_at'=>'01.01.2017', 'is_excluded'=>false],
            ['name'=>'Эксперт по закупкам', 'is_entered'=>true, 'entered_at'=>'01.01.2018', 'is_excluded'=>false],
            ['name'=>'Эксперт по закупкам (контракт.упр)', 'is_entered'=>true, 'entered_at'=>'04.05.2022', 'is_excluded'=>false],
            ['name'=>'Электромонтер', 'is_entered'=>true, 'entered_at'=>'01.01.2018', 'is_excluded'=>false],
            ['name'=>'Электромонтер по ремонту и обслуживанию электрооборудования 3 разряда', 'is_entered'=>true, 'entered_at'=>'01.06.2020', 'is_excluded'=>false],
            ['name'=>'Электромонтер по ремонту и обслуживанию электрооборудования 4 разряда', 'is_entered'=>true, 'entered_at'=>'01.06.2020', 'is_excluded'=>false],
            ['name'=>'юрисконсульт', 'is_entered'=>true, 'entered_at'=>'01.01.2016', 'is_excluded'=>false],
            ['name'=>'Юрисконсульт 1 категории', 'is_entered'=>true, 'entered_at'=>'01.01.2017', 'is_excluded'=>false],


        ];

        foreach($positions as $position){
            DB::table('positions')->insert(
                $position
            );
        };



    }
}
